# Generated by Django 3.0.6 on 2020-05-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditnews',
            name='redditDescription',
            field=models.TextField(),
        ),
    ]
