# Generated by Django 3.0.6 on 2020-05-23 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0002_auto_20200521_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videogame',
            old_name='release_date',
            new_name='released_date',
        ),
    ]
