# Generated by Django 3.0.6 on 2020-05-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0003_auto_20200523_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='isDiscount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videogame',
            name='isReleased',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videogame',
            name='slug',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videogameslist',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='preview_image',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='released_date',
            field=models.DateField(),
        ),
    ]
