# Generated by Django 3.0.6 on 2020-05-31 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0004_auto_20200531_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videogame',
            old_name='videoGamesList',
            new_name='videogameslist',
        ),
    ]
