# Generated by Django 3.0.6 on 2020-06-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0005_auto_20200531_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='preview_image',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
