# Generated by Django 3.0.6 on 2020-06-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0007_auto_20200602_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountrate',
            name='chosen_discount_percent',
            field=models.IntegerField(null=True),
        ),
    ]
