# Generated by Django 3.0.6 on 2020-06-13 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0009_auto_20200603_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountrate',
            name='videoGame',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notificationApp.VideoGame'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='genres',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='preview_image',
            field=models.ImageField(null=True, upload_to='game_pics'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
